// Objective-C API for talking to webserver Go package.
//   gobind -lang=objc webserver
//
// File is generated by gobind. Do not edit.

#ifndef __Webserver_H__
#define __Webserver_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class WebserverWebServer;

@interface WebserverWebServer : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nullable instancetype)init:(long)port fileDir:(NSString* _Nullable)fileDir;
- (BOOL)isRunning;
- (long)port;
// skipped method WebServer.Routes with unsupported parameter or return types

- (BOOL)run:(NSError* _Nullable* _Nullable)error;
- (NSString* _Nonnull)serverURL;
- (BOOL)stop:(NSError* _Nullable* _Nullable)error;
@end

// skipped function FileServer with unsupported parameter or return types


FOUNDATION_EXPORT BOOL WebserverGetWebServerPort(long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT WebserverWebServer* _Nullable WebserverNewWebServer(long port, NSString* _Nullable fileDir, NSError* _Nullable* _Nullable error);

/**
 * NOTE: make sure to call this method before starting the server
TODO: rename this to SetFileDir
 */
FOUNDATION_EXPORT void WebserverSetConfig(NSString* _Nullable fileDir);

/**
 * NOTE: make sure to call this method before starting the server
 */
FOUNDATION_EXPORT void WebserverSetPort(long port);

FOUNDATION_EXPORT NSString* _Nonnull WebserverStart(NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL WebserverStartWebServer(long port, NSString* _Nullable fileDir, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT void WebserverStop(void);

FOUNDATION_EXPORT NSString* _Nonnull WebserverUrl(void);

#endif
